title: CUELLAR TECH SOFT
author: cuellartechsoft
email: cuellar.tech.soft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Soluciones informáticas y tecnológicas para tu empresa

twitter_username: nono
github_username:  cuellartechsoft

sass:
    style: compressed
